# Generated by Django 4.1.3 on 2022-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Author', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('review', models.IntegerField(max_length=10)),
            ],
        ),
    ]
