# Generated by Django 4.1.3 on 2022-12-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='bookdata',
            name='review',
        ),
        migrations.AddField(
            model_name='bookdata',
            name='image',
            field=models.ImageField(default='https://cor-cdn-static.bibliocommons.com/assets/default_covers/icon-book-93409e4decdf10c55296c91a97ac2653.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='bookdata',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
