# Generated by Django 4.1.3 on 2022-12-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_bookdata_author_remove_bookdata_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdata',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
