# Generated by Django 4.1.3 on 2022-12-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_genre_bookdata_genre_alter_bookdata_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='description',
            field=models.CharField(default='description', max_length=300),
        ),
    ]
