# Generated by Django 4.1.3 on 2022-12-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookdata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='image',
            field=models.ImageField(default='media/none/noimg.jpg', upload_to='media'),
        ),
    ]
